#markdown: kramdown
markdown: rdiscount
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: hydroxygen
host: hydroxygen.github.com

custom:
    category:
        notes: 推荐系统学习笔记       
    categories:
      - name:  notes
        title: 推荐系统学习笔记
meta:
    author:
        name: hydroxygen
        email: hydroxygen@163.com
        disqus: hydroxygen 			                # Disqus缩略标识
        gcse: 002981071471006019237:bcmd-n00ura     # Google自定义搜索标识ID
        github: hydroxygen             			    # GitHub账号
        gravatar: 8f021a48ca93da3a7729e7b89f3e6cdc  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
