markdown: rdiscount
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: hydroxygen
host: hydroxygen.github.com

custom:
    category:
        notes: 推荐系统学习笔记       
    categories:
      - name:  notes
        title: 推荐系统学习笔记
meta:
    author:
        name: hydroxygen
        email: hydroxygen@163.com       
        gravatar: 8f021a48ca93da3a7729e7b89f3e6cdc  # Gravatar头像标识
   
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
